workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: europe-west1-docker.pkg.dev/rare-mechanic-447712-n4/pixel-art-diffuser/train:lattest
    command: ["python", "-m", "src.pixel_art_diffusion.train"]
    args: [
      "--run-name", "vertex-training",
      "--num-epochs", "100",
      "--label-subset", "3"
    ]